
export class MenuItemsInput{
    RoleID : number;
}

export class MenuItemsOutput{
    menuLists! : MenuItem [] ;
    status: string;
    message: string;
}

export class MenuItem{
    menuID: number;
    menuName: string;
    moduleID: number;
    level: number;
    parentMenuID: number;
    sequence: number;
    url: string;
    rowSequence : number;
    IsHidd : number;
    AllowView : number;
    AllowAdd : number;
    AlloDele : number;
    AlloModi : number;
    AlloSave : number;
    AlloEmai : number;   
    AlloPrin : number;
    AlloExpo : number;
}

export const NEW_MENUS = [
    {
        "menuID": 3000,
        "menuName": "New Data Entry",
        "moduleID": 1,
        "level": 0,
        "parentMenuID": 0,
        "sequence": 0,
        "url": "",
        "rowSequence": 4,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true
    },
    {
        "menuID": 3001,
        "menuName": "LIC Policy Entry",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 1,
        "url": "data-entry/lic-policy",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "soon" : false,
        "beta" : true

    },
    // {
    //     "menuID": 3002,
    //     "menuName": "Premium Deposit Entry",
    //     "moduleID": 1,
    //     "level": 2,
    //     "parentMenuID": 3000,
    //     "sequence": 2,
    //     "url": "data-entry/premium-deposite",
    //     "rowSequence": 0,
    //     "aspSequence": 4,
    //     "aspRowSeq": 0,
    //     "isHidd": 0,
    //     "alloView": 1,
    //     "allowAdd": 0,
    //     "allowDelete": 0,
    //     "allowModify": 0,
    //     "allowSave": 0,
    //     "allowEmail": 0,
    //     "allowPrint": 0,
    //     "allowExport": 0,
    //     "applicationID": 4,
    //     "isPosp": 1,
    // },
    {
        "menuID": 3003,
        "menuName": "Family History",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 3,
        "url": "data-entry/family-history",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false

    },
    {
        "menuID": 3004,
        "menuName": "Medical History",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 4,
        "url": "data-entry/medical-history",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false

    },
    {
        "menuID": 3005,
        "menuName": "Annuity Existence",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 5,
        "url": "data-entry/annuity-existence",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false

    },
    {
        "menuID": 3006,
        "menuName": "Advance taken from LIC",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 6,
        "url": "data-entry/advance-taken",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false
    },
    {
        "menuID": 3007,
        "menuName": "Commission Receipts",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 7,
        "url": "data-entry/commission-receipt",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false
    },
    {
        "menuID": 3008,
        "menuName": "Loan Surrender Value",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 7,
        "url": "reports/loan-quotation-calculator",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false
    },
    {
        "menuID": 3008,
        "menuName": "Cheque Dishonoured",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 8,
        "url": "data-entry/cheque-dishounoured",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "beta":true,
        "soon":false,
        "angular" : true
    },
    {
        "menuID": 3009,
        "menuName": "Loan Taken and Repaid",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 9,
        "url": "data-entry/loan-transaction",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false
    },
    {
        "menuID": 3010,
        "menuName": "N.B. BOC",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 3000,
        "sequence": 10,
        "url": "data-entry/nboc-transaction",
        "rowSequence": 0,
        "aspSequence": 4,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false
    },
    {
        "menuID": 4000,
        "menuName": "LIC Reports",
        "moduleID": 1,
        "level": 0,
        "parentMenuID": 0,
        "sequence": 0,
        "url": "",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        "angular" : true
    },
    {
        "menuID": 4001,
        "menuName": "Policy Register",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 0,
        "url": "reports/policy-register",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        "angular" : true
    },
    {
        "menuID": 4002,
        "menuName": "Current Status Register",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/current-status",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false
    },
    {
        "menuID": 4003,
        "menuName": "Premiums Due",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/premium-due",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        "angular" : true
    },
    {
        "menuID": 4004,
        "menuName": "Premiums Outstanding",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/premium-outstanding",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        "angular" : true
    },
    {
        "menuID": 4005,
        "menuName": "Lapsed Policy",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/lapsed-policies",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        "angular" : true
    },
    {
        "menuID": 4006,
        "menuName": "Policy Maturity",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/maturity",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        "angular" : true
    },
    {
        "menuID": 4007,
        "menuName": "Survival Benefit",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/survival-benefits",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        "angular" : true
    },
    {
        "menuID": 4008,
        "menuName": "Cash Flow Chart",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/cashflow-chart",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta":true,
        "soon":false
    },
    {
        "menuID": 4009,
        "menuName": "Comprehensive Insurance Chart",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/comprehensive-insure-chart",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta" : true,
        "soon": false
    },
    {
        "menuID": 4010,
        "menuName": "Commision Ledger",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 4000,
        "sequence": 1,
        "url": "reports/commission-ledger",
        "rowSequence": 0,
        "aspSequence": 2,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "beta" : true,
        "soon": false
    },
    {
        "menuID": 5000,
        "menuName": "LIC Presentation",
        "moduleID": 1,
        "level": 0,
        "parentMenuID": 0,
        "sequence": 1,
        "url": "",
        "rowSequence": 0,
        "aspSequence": 1,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true
    },
    {
        "menuID": 5001,
        "menuName": "Magic Mix",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 5000,
        "sequence": 1,
        "url": "presentation/magic-mix",
        "rowSequence": 0,
        "aspSequence": 1,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true,
        "soon" : true,
        "beta" : false
    } , 
    {
        "menuID": 6000,
        "menuName": "Single Plan Presentation",
        "moduleID": 1,
        "level": 0,
        "parentMenuID": 0,
        "sequence": 1,
        "url": "",
        "rowSequence": 0,
        "aspSequence": 1,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true
    },
    {
        "menuID": 6001,
        "menuName": "New Endowment Plan - 914",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 5000,
        "sequence": 1,
        "url": "presentation/single-plan",
        "rowSequence": 0,
        "aspSequence": 1,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true
    },
    {
        "menuID": 14,
        "menuName": "Premium Paid Certificate",
        "moduleID": 1,
        "level": 2,
        "parentMenuID": 10, 
        "sequence": 4,
        "url": "reports/premium-certificate",
        "rowSequence": 0,
        "aspSequence": 1,
        "aspRowSeq": 0,
        "isHidd": 0,
        "alloView": 1,
        "allowAdd": 0,
        "allowDelete": 0,
        "allowModify": 0,
        "allowSave": 0,
        "allowEmail": 0,
        "allowPrint": 0,
        "allowExport": 0,
        "applicationID": 4,
        "isPosp": 1,
        // "show" : false,
        "angular" : true
    },
];
